repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: black .
      language: system
      types: [ python ]
    - id: pylint
      name: pylint
      entry: pylint kobject
      language: system
      types: [python]
      args:
        [
          "--ignore-paths",
          "tests/",
          "--disable=C0114,C0115,C0116,R0903",
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      types: [ python ]
      pass_filenames: false
      always_run: true
    - id: mutatest
      name: mutatest
      entry: mutatest
      language: system
      types: [ python ]
      args:
        [
          "-n",
          "100",
          "-s",
          "loglifos",
        ]
      pass_filenames: false
      always_run: true